//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.SvcCuenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcCuenta.IIServicioCuenta")]
    public interface IIServicioCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioCuenta/ValidarUsuario", ReplyAction="http://tempuri.org/IIServicioCuenta/ValidarUsuarioResponse")]
        bool ValidarUsuario(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioCuenta/ValidarUsuario", ReplyAction="http://tempuri.org/IIServicioCuenta/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIServicioCuentaChannel : WebApp.SvcCuenta.IIServicioCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IServicioCuentaClient : System.ServiceModel.ClientBase<WebApp.SvcCuenta.IIServicioCuenta>, WebApp.SvcCuenta.IIServicioCuenta {
        
        public IServicioCuentaClient() {
        }
        
        public IServicioCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IServicioCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicioCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicioCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string username, string password) {
            return base.Channel.ValidarUsuario(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string username, string password) {
            return base.Channel.ValidarUsuarioAsync(username, password);
        }
    }
}
