//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.SvcJuegos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcJuegos.IServicioJuegos")]
    public interface IServicioJuegos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoServicioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Juegos.Negocio.Modelo.JuegoCasual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Juegos.Negocio.Modelo.JuegoExtremo))]
        Juegos.Negocio.Modelo.Juego BuscarUnoJuegoServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoServicioResponse")]
        System.Threading.Tasks.Task<Juegos.Negocio.Modelo.Juego> BuscarUnoJuegoServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoByNombreServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoByNombreServicioResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Juegos.Negocio.Modelo.JuegoCasual))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Juegos.Negocio.Modelo.JuegoExtremo))]
        Juegos.Negocio.Modelo.Juego BuscarUnoJuegoByNombreServicio(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoByNombreServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoByNombreServicioResponse")]
        System.Threading.Tasks.Task<Juegos.Negocio.Modelo.Juego> BuscarUnoJuegoByNombreServicioAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/CrearJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/CrearJuegoCasualServicioResponse")]
        bool CrearJuegoCasualServicio(string nombre, bool requiereSupervision, bool poseeCinturon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/CrearJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/CrearJuegoCasualServicioResponse")]
        System.Threading.Tasks.Task<bool> CrearJuegoCasualServicioAsync(string nombre, bool requiereSupervision, bool poseeCinturon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/UpdateJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/UpdateJuegoCasualServicioResponse")]
        bool UpdateJuegoCasualServicio(int id, string nombre, bool requiereSupervision, bool poseeCinturon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/UpdateJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/UpdateJuegoCasualServicioResponse")]
        System.Threading.Tasks.Task<bool> UpdateJuegoCasualServicioAsync(int id, string nombre, bool requiereSupervision, bool poseeCinturon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/DeleteJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/DeleteJuegoCasualServicioResponse")]
        bool DeleteJuegoCasualServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/DeleteJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/DeleteJuegoCasualServicioResponse")]
        System.Threading.Tasks.Task<bool> DeleteJuegoCasualServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualServicioResponse")]
        Juegos.Negocio.Modelo.JuegoCasual BuscarUnoJuegoCasualServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualServicioResponse")]
        System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoCasual> BuscarUnoJuegoCasualServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualByNombreServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualByNombreServicioResponse")]
        Juegos.Negocio.Modelo.JuegoCasual BuscarUnoJuegoCasualByNombreServicio(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualByNombreServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoCasualByNombreServicioResponse")]
        System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoCasual> BuscarUnoJuegoCasualByNombreServicioAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/CrearJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/CrearJuegoExtremoServicioResponse")]
        bool CrearJuegoExtremoServicio(string nombre, int altura, int nivelRiesgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/CrearJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/CrearJuegoExtremoServicioResponse")]
        System.Threading.Tasks.Task<bool> CrearJuegoExtremoServicioAsync(string nombre, int altura, int nivelRiesgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/UpdateJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/UpdateJuegoExtremoServicioResponse")]
        bool UpdateJuegoExtremoServicio(int id, string nombre, int altura, int nivelRiesgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/UpdateJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/UpdateJuegoExtremoServicioResponse")]
        System.Threading.Tasks.Task<bool> UpdateJuegoExtremoServicioAsync(int id, string nombre, int altura, int nivelRiesgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/DeleteJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/DeleteJuegoExtremoServicioResponse")]
        bool DeleteJuegoExtremoServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/DeleteJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/DeleteJuegoExtremoServicioResponse")]
        System.Threading.Tasks.Task<bool> DeleteJuegoExtremoServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoServicioResponse")]
        Juegos.Negocio.Modelo.JuegoExtremo BuscarUnoJuegoExtremoServicio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoServicioResponse")]
        System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoExtremo> BuscarUnoJuegoExtremoServicioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoByNombreServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoByNombreServicioResponse")]
        Juegos.Negocio.Modelo.JuegoExtremo BuscarUnoJuegoExtremoByNombreServicio(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoByNombreServicio", ReplyAction="http://tempuri.org/IServicioJuegos/BuscarUnoJuegoExtremoByNombreServicioResponse")]
        System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoExtremo> BuscarUnoJuegoExtremoByNombreServicioAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioJuegosChannel : WebApp.SvcJuegos.IServicioJuegos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioJuegosClient : System.ServiceModel.ClientBase<WebApp.SvcJuegos.IServicioJuegos>, WebApp.SvcJuegos.IServicioJuegos {
        
        public ServicioJuegosClient() {
        }
        
        public ServicioJuegosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioJuegosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJuegosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJuegosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Juegos.Negocio.Modelo.Juego BuscarUnoJuegoServicio(int id) {
            return base.Channel.BuscarUnoJuegoServicio(id);
        }
        
        public System.Threading.Tasks.Task<Juegos.Negocio.Modelo.Juego> BuscarUnoJuegoServicioAsync(int id) {
            return base.Channel.BuscarUnoJuegoServicioAsync(id);
        }
        
        public Juegos.Negocio.Modelo.Juego BuscarUnoJuegoByNombreServicio(string nombre) {
            return base.Channel.BuscarUnoJuegoByNombreServicio(nombre);
        }
        
        public System.Threading.Tasks.Task<Juegos.Negocio.Modelo.Juego> BuscarUnoJuegoByNombreServicioAsync(string nombre) {
            return base.Channel.BuscarUnoJuegoByNombreServicioAsync(nombre);
        }
        
        public bool CrearJuegoCasualServicio(string nombre, bool requiereSupervision, bool poseeCinturon) {
            return base.Channel.CrearJuegoCasualServicio(nombre, requiereSupervision, poseeCinturon);
        }
        
        public System.Threading.Tasks.Task<bool> CrearJuegoCasualServicioAsync(string nombre, bool requiereSupervision, bool poseeCinturon) {
            return base.Channel.CrearJuegoCasualServicioAsync(nombre, requiereSupervision, poseeCinturon);
        }
        
        public bool UpdateJuegoCasualServicio(int id, string nombre, bool requiereSupervision, bool poseeCinturon) {
            return base.Channel.UpdateJuegoCasualServicio(id, nombre, requiereSupervision, poseeCinturon);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateJuegoCasualServicioAsync(int id, string nombre, bool requiereSupervision, bool poseeCinturon) {
            return base.Channel.UpdateJuegoCasualServicioAsync(id, nombre, requiereSupervision, poseeCinturon);
        }
        
        public bool DeleteJuegoCasualServicio(int id) {
            return base.Channel.DeleteJuegoCasualServicio(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteJuegoCasualServicioAsync(int id) {
            return base.Channel.DeleteJuegoCasualServicioAsync(id);
        }
        
        public Juegos.Negocio.Modelo.JuegoCasual BuscarUnoJuegoCasualServicio(int id) {
            return base.Channel.BuscarUnoJuegoCasualServicio(id);
        }
        
        public System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoCasual> BuscarUnoJuegoCasualServicioAsync(int id) {
            return base.Channel.BuscarUnoJuegoCasualServicioAsync(id);
        }
        
        public Juegos.Negocio.Modelo.JuegoCasual BuscarUnoJuegoCasualByNombreServicio(string nombre) {
            return base.Channel.BuscarUnoJuegoCasualByNombreServicio(nombre);
        }
        
        public System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoCasual> BuscarUnoJuegoCasualByNombreServicioAsync(string nombre) {
            return base.Channel.BuscarUnoJuegoCasualByNombreServicioAsync(nombre);
        }
        
        public bool CrearJuegoExtremoServicio(string nombre, int altura, int nivelRiesgo) {
            return base.Channel.CrearJuegoExtremoServicio(nombre, altura, nivelRiesgo);
        }
        
        public System.Threading.Tasks.Task<bool> CrearJuegoExtremoServicioAsync(string nombre, int altura, int nivelRiesgo) {
            return base.Channel.CrearJuegoExtremoServicioAsync(nombre, altura, nivelRiesgo);
        }
        
        public bool UpdateJuegoExtremoServicio(int id, string nombre, int altura, int nivelRiesgo) {
            return base.Channel.UpdateJuegoExtremoServicio(id, nombre, altura, nivelRiesgo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateJuegoExtremoServicioAsync(int id, string nombre, int altura, int nivelRiesgo) {
            return base.Channel.UpdateJuegoExtremoServicioAsync(id, nombre, altura, nivelRiesgo);
        }
        
        public bool DeleteJuegoExtremoServicio(int id) {
            return base.Channel.DeleteJuegoExtremoServicio(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteJuegoExtremoServicioAsync(int id) {
            return base.Channel.DeleteJuegoExtremoServicioAsync(id);
        }
        
        public Juegos.Negocio.Modelo.JuegoExtremo BuscarUnoJuegoExtremoServicio(int id) {
            return base.Channel.BuscarUnoJuegoExtremoServicio(id);
        }
        
        public System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoExtremo> BuscarUnoJuegoExtremoServicioAsync(int id) {
            return base.Channel.BuscarUnoJuegoExtremoServicioAsync(id);
        }
        
        public Juegos.Negocio.Modelo.JuegoExtremo BuscarUnoJuegoExtremoByNombreServicio(string nombre) {
            return base.Channel.BuscarUnoJuegoExtremoByNombreServicio(nombre);
        }
        
        public System.Threading.Tasks.Task<Juegos.Negocio.Modelo.JuegoExtremo> BuscarUnoJuegoExtremoByNombreServicioAsync(string nombre) {
            return base.Channel.BuscarUnoJuegoExtremoByNombreServicioAsync(nombre);
        }
    }
}
