//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int cuentaID { get; set; }
        public string cuentaUsuario { get; set; }
        public string cuentaPassword { get; set; }
    }
}
