//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int empleadoID { get; set; }
        public string empleadoNombre { get; set; }
        public short empleadoEdad { get; set; }
        public int empleadoTrabajoID { get; set; }
    }
}
