//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int empleadoID { get; set; }
        public string empleadoNombre { get; set; }
        public short empleadoEdad { get; set; }
        public int empleadoTrabajoID { get; set; }
    }
}
