//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuegosCasuales
    {
        public int juegoID { get; set; }
        public bool juegoCasualPoseeCinturon { get; set; }
        public bool juegoCasualReqSupervision { get; set; }
    
        public virtual Juegos Juegos { get; set; }
    }
}
