//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juegos
    {
        public int juegoID { get; set; }
        public string juegoNombre { get; set; }
        public byte juegoTipo { get; set; }
        public Nullable<byte> juegoCasualPoseeCinturon { get; set; }
        public Nullable<byte> juegoCasualReqSupervision { get; set; }
        public Nullable<int> juegoExtremoNivelRiesgo { get; set; }
        public Nullable<int> juegoExtremoAltura { get; set; }
    }
}
